apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: payment-service-scaler
  namespace: default
  labels:
    app: payment-service
    role: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service-deployment
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 5
  cooldownPeriod: 30
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
            - type: Percent
              value: 50
              periodSeconds: 15
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: payment.order_created.queue
        mode: QueueLength
        value: "30"
      authenticationRef:
        name: rabbitmq-keda-auth
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-keda-auth
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-credentials
      key: host
