apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: payment-service-scaledobject
  namespace: ecom
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service-deployment
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 30
  pollingInterval: 5
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: payment.order_created.queue
        mode: QueueLength
        value: "10"
      authenticationRef:
        name: rabbitmq-trigger-auth
