global:
  resolve_timeout: 5m

route:
  receiver: 'webhook-demo'
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: 'webhook-demo'
    webhook_configs:
      - url: 'https://webhook.site/50f62265-d407-4c3c-9335-fa68d7782696'
        send_resolved: true
