apiVersion: v1
kind: Service
metadata:
  name: metrics-stub
  labels:
    app: metrics-stub
spec:
  selector:
    app: metrics-stub
  ports:
    - name: metrics
      port: 9000
      targetPort: 9000