apiVersion: v1
kind: ConfigMap
metadata:
  name: ecom-config
  namespace: ecom
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  USER_SERVICE_PORT: "3001"
  CATALOG_SERVICE_PORT: "3002"
  ORDER_SERVICE_PORT: "3003"
  PAYMENT_SERVICE_PORT: "3004"
  USER_SERVICE_URL: "http://user-service.ecom.svc.cluster.local:3001"
  CATALOG_SERVICE_URL: "http://catalog-service.ecom.svc.cluster.local:3002"
  ORDER_SERVICE_URL: "http://order-service.ecom.svc.cluster.local:3003"
  PAYMENT_SERVICE_URL: "http://payment-service.ecom.svc.cluster.local:3004"
  REDIS_URL: "redis://ecom-redis.ecom.svc.cluster.local:6379"
  RABBITMQ_URL: "amqp://guest:guest@ecom-rabbitmq.ecom.svc.cluster.local:5672"
  RABBITMQ_EXCHANGE: "ecommerce"
  JWT_EXPIRES_IN: "1d"
