apiVersion: v1
kind: Service
metadata:
  name: ecom-postgres
  namespace: ecom
spec:
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ecom-postgres
  namespace: ecom
subsets:
  - addresses:
      - ip: 172.18.0.1
    ports:
      - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-redis
  namespace: ecom
spec:
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ecom-redis
  namespace: ecom
subsets:
  - addresses:
      - ip: 172.18.0.1
    ports:
      - port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-rabbitmq
  namespace: ecom
spec:
  ports:
    - port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ecom-rabbitmq
  namespace: ecom
subsets:
  - addresses:
      - ip: 172.18.0.1
    ports:
      - port: 5672

