apiVersion: v1
kind: Secret
metadata:
  name: ecom-secret
  namespace: ecom
type: Opaque
stringData:
  JWT_SECRET: "super-secret-jwt-key-change-in-production"
  DATABASE_URL_USER: "postgresql://postgres:postgres@ecom-postgres.ecom.svc.cluster.local:5432/user_db?schema=public"
  DATABASE_URL_CATALOG: "postgresql://postgres:postgres@ecom-postgres.ecom.svc.cluster.local:5432/catalog_db?schema=public"
  DATABASE_URL_ORDER: "postgresql://postgres:postgres@ecom-postgres.ecom.svc.cluster.local:5432/order_db?schema=public"
  DATABASE_URL_PAYMENT: "postgresql://postgres:postgres@ecom-postgres.ecom.svc.cluster.local:5432/payment_db?schema=public"
  DATABASE_URL: "postgresql://postgres:postgres@ecom-postgres.ecom.svc.cluster.local:5432/user_db?schema=public"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
